name: Binance Proxy Bot

on:
  schedule:
    - cron: '50 19 * * *' # 2g VN
    - cron: '50 0 * * *' # 8g VN
    - cron: '50 7 * * *' # 15g VN
    - cron: '50 12 * * *' # 20g VN
    - cron: '50 14 * * *' # 22g VN
    
  workflow_dispatch:      # Bấm chạy tay để test

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install pandas requests
      - name: Execute Script
        env:
          TELE_TOKEN: ${{ secrets.TELE_TOKEN }}
          TELE_CHATID: ${{ secrets.TELE_CHATID }}
        run: python bot_rsi_github.py
